##this file is called pod manifest file.
##create and display pods; test & validate

apiVersion: v1
kind: Pod
metadata:
        name: nginx-pod
        labels:
                app: nginx
                tier: dev
spec:
        containers:
              - name: nginx-container
                image: nginx 
