apiVersion: v1
kind: ReplicationController
metadata:
        name: nginx-rc

spec:
        replicas: 3
        selector:
                app: nginx-app  ##this value should be same as labels of template 

        template:
                metadata:                ## from here it's pod defination
                        name: nginx-pod
                        labels:
                                app: nginx-app
                spec:
                        containers:
                              - name: nginx-container
                                image: nginx
                                ports:
                                - containerPort: 80
